### ISSUE TITLE
Project is outdated and broken

### ISSUE THREAD

**Issue by rocketkittens** [Unity-Technologies/FPSSample#104]
It is not possible to successfully load this project. I have tried with several different version of Unity.

This project is outdated and broken.

**Comment by Creepysin** [comment]
It opens fine for me using Unity `2018.3.8f1`.

What errors are you getting?

Also make sure you have Git LFS when cloning the project, as it says on the readme.

**Comment by rocketkittens** [comment]
Thanks @Creepysin, the readme is important. I have better result after using git lfs.
