### ISSUE TITLE
Where is the source code reflect the design concept of "send duplicated client command"?

### ISSUE THREAD

**Issue by qq995002966** [Unity-Technologies/FPSSample#109]
Hi, unity guys,
Where is the source code relfect the design concept of "send duplicated client command" in the follow figure ?

![问题](https://github.com/qq995002966/testEmpty/blob/master/%E9%97%AE%E9%A2%98.png?raw=true)

**Comment by qq995002966** [comment]
I found it after almost one Month. In ClientGameLoop.HandleTime
```
         if (m_PredictedTime.tick > prevTick) {
            var oldestCommandToSend = Mathf.Max(prevTick, m_PredictedTime.tick - NetworkConfig.commandClientBufferSize);
            for (int tick = oldestCommandToSend; tick < m_PredictedTime.tick; tick++) {
                m_PlayerModule.StoreCommand(tick);// store old command
                m_PlayerModule.SendCommand(tick); //send command called in handle time ^_^
            }

            m_PlayerModule.ResetInput(userInputEnabled);
            m_PlayerModule.StoreCommand(m_PredictedTime.tick);
        }

```

**Comment by ArnaudValensi** [comment]
According to my understanding, the last command is added to a commandBuffer at [PlayerModuleClient.cs:165](https://github.com/Unity-Technologies/FPSSample/blob/master/Assets/Scripts/Game/Modules/Player/PlayerModuleClient.cs#L165)

ClientGameWorld.Update() → HandleTime() → StoreCommand() → StoreCommand() 

`localPlayer.commandBuffer.Add(ref localPlayer.command, tick);`


The command is then retrieved at [PlayerModuleClient.cs:206](https://github.com/Unity-Technologies/FPSSample/blob/master/Assets/Scripts/Game/Modules/Player/PlayerModuleClient.cs#L206) and re-enqueud to the `localPlayer.networkClient` at [PlayerModuleClient.cs:217](https://github.com/Unity-Technologies/FPSSample/blob/master/Assets/Scripts/Game/Modules/Player/PlayerModuleClient.cs#L217)

ClientGameWorld.Update() → HandleTime() → SendCommand()


Added in the commandsOut at [NetworkClient.cs:378](https://github.com/Unity-Technologies/FPSSample/blob/master/Assets/Scripts/Networking/NetworkClient.cs#L378)

ClientGameWorld.Update() → HandleTime() → SendCommand() → QueueCommand() → QueueCommand()

```csharp
unsafe public void QueueCommand(int time, DataGenerator generator)
{
    ...
    var info = commandsOut.Acquire(++commandSequence);

    info.time = time;
    fixed (uint* buf = info.data)
    {
        // The buf variable is the one of the 3 element of the ring buffer (SequenceBuffer)
        var writer = new NetworkWriter(buf, info.data.Length, commandSchema, generateSchema);
        generator(ref writer);
        writer.Flush();
    }
}
```

The commandsOut is declared as follow:

```csharp
SequenceBuffer<CommandInfo> commandsOut = new SequenceBuffer<CommandInfo>(3, () => new CommandInfo());
```

This is a ring buffer with the capacity of 3 for the last 3 commands.


The SequenceBuffer is written into the network stream to be sent to the server in [NetworkClient.cs:975](https://github.com/Unity-Technologies/FPSSample/blob/master/Assets/Scripts/Networking/NetworkClient.cs#L975)

ClientGameWorld.Update() → SendData() → SendPackage() → WriteCommands()

So the only difference with the design concept is that only the 3 last commands are sent.

**Comment by qq995002966** [comment]
I undertood it finally , thank you ArnaudValensi . f(￣▽￣)~*

**Comment by ArnaudValensi** [comment]
You're welcome :)
