### ISSUE TITLE
Opening FPSSample 

### ISSUE THREAD

**Issue by BigDru** [Unity-Technologies/FPSSample#114]
Aside from a previous issue which mentioned that FPSSample will not properly open in any newer version of Unity. I went ahead and downloaded 2018.3.8f1 specifically and I'm still unable to get the packages working properly. 

![image](https://user-images.githubusercontent.com/3673996/79704616-35e75800-8280-11ea-9808-c0057623b189.png)

Shouldn't there be, at the very least, an effort to maintain the project with the previous version?

I tried looking at 127.0.0.1:10010/health and got the following:
{"status":"OK","nodeVersion":"v8.11.3","upmVersion":"v2.7.4"}

**Comment by PiParmy** [comment]
Delete the file FPSSample\Packages\manifest.json and open it again. You will be on to the next issue bug :) Sorry that is the one I am stuck on now. Let me know if you get past this one.

**Comment by BigDru** [comment]
Thanks. That got me a little further. Now I'm getting errors that NativeQueue<> and NativeList<> types cannot be found. 

Google says they should be part of the Unity.Collections package. However, I don't seem to have them listed as detected types under the package in VS. 
![image](https://user-images.githubusercontent.com/3673996/80027313-8e516c00-84b1-11ea-9396-99da64a7f65a.png)
 
Another error is that the editor cannot find the Unity.Mathematics package.
![image](https://user-images.githubusercontent.com/3673996/80027417-bb058380-84b1-11ea-8260-3a419b73af29.png)

**Comment by BigDru** [comment]
The previous manifested had the following line: 
    "com.unity.mathematics": "0.0.12-preview.21",
while the deleted one did not so I tried adding it back to the manifest. 

I still left out the line:
"registry": "https://staging-packages.unity.com"

But now I'm getting a similar error to before. 

![image](https://user-images.githubusercontent.com/3673996/80028317-ee94dd80-84b2-11ea-8789-4b6dbf0c10f5.png)

**Comment by BigDru** [comment]
Ok update. I tried specifying the github location for the Unity.Mathematics package as that feature was apparently added in 2018.3.0. 

That didn't work, however. The reason was that the package.json that the Unity Package Manager was looking for was in the src subfolder. And with no way to specify a specific subfolder in git I needed to download that specific commit to my local drive and reference it in my manifest as such:

![image](https://user-images.githubusercontent.com/3673996/80032081-a5e02300-84b8-11ea-9440-cfbd82c39884.png)

After a really long reimport I seem to have solved the previous errors. I'm going to keep this issue open for a few more days however. I no longer have time today to analyze if everything is working ok. 

In the future I may add the Unity.Mathematics package as a submodule and modify the manifest to point to a copy of the src folder within the FPS sample project. Then I'll issue a pull request. But first I need to make sure the project is fully working.

**Comment by advra** [comment]
Having similar issues. Where do I find the mathematics package?

**Comment by idlejob** [comment]
**_Don't delete the manifest.json, just change it up a bit._** 

**change the line** > 
`"registry": "https://staging-packages.unity.com"`

**to** >    
```
 "testables": [
    "com.unity.test-framework.performance"
  ]
```

![1](https://user-images.githubusercontent.com/56068352/80666001-e22ef880-8a4f-11ea-8786-4fe4a86727fc.PNG)


**and change the Mathematics line also to** 
`"com.unity.mathematics": "0.0.12-preview.20"`

The mathematics version is originally 0.0.12-preview.21, but I found out on other forums that  0.0.12-preview.20 works. Tested it out for myself and it worked. 

it should look like this 
![2](https://user-images.githubusercontent.com/56068352/80665956-be6bb280-8a4f-11ea-8f36-91a7b74bc84c.PNG)

After that, you should be able to open the project, reimport all assets to avoid any errors, then restart the project, and you should be able to see the "FPS Sample" tab where the "Project Tools" is located. Hope it works for you.

**Comment by BigDru** [comment]
Excellent! This is exactly what I was looking for. I found that the staging packages has long since been decommissioned but could not find a replacement. Was going to manually link all the missing packages locally. 

I've managed to load up Level_00 with com.unity.mathematics package 0.0.12-preview.20 as you suggested.
