### ISSUE TITLE
Completely broken - 

### ISSUE THREAD

**Issue by Nolram12345** [Unity-Technologies/FPSSample#123]
When trying to open the project the following error is thrown : 
![grafik](https://user-images.githubusercontent.com/37701550/92155969-8b379680-ee28-11ea-85b8-75cb73eb1e69.png)

When I hit continue, the console is totally flooded with errors about missing assemblies and various parameters.
Is this a known issue ? How/Can this be fixed ?

**Comment by Nolram12345** [comment]
The package manager is also broken aswell.
![grafik](https://user-images.githubusercontent.com/37701550/92156122-ce920500-ee28-11ea-9184-37b908770dd7.png)

**Comment by SaumitraVerma** [comment]
Which Version of Unity are you using

**Comment by SaumitraVerma** [comment]
Did you install git lfs before cloning??

**Comment by Nolram12345** [comment]
1. I have enabled preview packages.
2. I have installed git LFS, and all the files are there (its about 18GB like it should be).

**Comment by Nolram12345** [comment]
3. I am using Unity 2018.3.8f1 (the version that it says you should use in the readme.md)

**Comment by ylme** [comment]
see https://github.com/Unity-Technologies/FPSSample/issues/114

**Comment by ylme** [comment]
https://github.com/Unity-Technologies/FPSSample/issues/114#issuecomment-618048667 solved my problem, maybe the same with yours.

**Comment by Nolram12345** [comment]
This has mostly worked, however there are still 2 issues : 
These errors 
![grafik](https://user-images.githubusercontent.com/37701550/92243159-50ce0800-eec1-11ea-9351-dabe18b870e2.png)
and that every scene is black with only the 3D icons showing up.

**Comment by ylme** [comment]
> 
> 
> This has mostly worked, however there are still 2 issues :
> These errors
> ![grafik](https://user-images.githubusercontent.com/37701550/92243159-50ce0800-eec1-11ea-9351-dabe18b870e2.png)
> and that every scene is black with only the 3D icons showing up.

try `git cleanup -fd` to cleanup the project, then just modify according https://github.com/Unity-Technologies/FPSSample/issues/114 . make sure Library\PackageCache is empty.

**Comment by Nolram12345** [comment]
I have tried doing cleanup, but it gave me an error. I have modified the project according #114 . I have also cleaned the package cache. Issues persist.

**Comment by SaumitraVerma** [comment]
https://forum.unity.com/threads/kernel-ksamplecopy4_1_x_8-not-found-under-unity-2018-3.597463/

This is your first error. it says to reimport the render pipeline.

**Comment by Nolram12345** [comment]
I can't reimport HDRP, it doesn't show me any options for it.
![grafik](https://user-images.githubusercontent.com/37701550/92252167-2767a900-eece-11ea-96be-8845b2cc7f5c.png)

**Comment by Nolram12345** [comment]
Update : I managed to fix it my manually reimporting the HDRP folder. Thanks for the help !
