### ISSUE TITLE
Maximum number (256) of shader keywords exceeded

### ISSUE THREAD

**Issue by Peaj** [Unity-Technologies/FPSSample#13]
There seem to bee too many shader keywords in the project as I am getting alot of these errors:
Maximum number (256) of shader keywords exceeded, keyword _DISTORTIONDEPTHTEST_OFF will be ignored.
Also everything is white when starting Level_01 in editor playmode.
I assume this could be a result of failed shader compilation?

**Comment by hayes87** [comment]
Try restarting unity, it worked for me

**Comment by Peaj** [comment]
You are right. The error messages went away after the restart, Still seems suspicious to me as shader keywords wouldnt magically vanish would they?

**Comment by pandr** [comment]
This is a known issue and unfortunately there is no other fix than the workaround of restarting Unity right now. (It is a Unity limitation and I believe a fix is underway but I don't know the timeframe).
