### ISSUE TITLE
Do you plan for network simulate?

### ISSUE THREAD

**Issue by Jennal** [Unity-Technologies/FPSSample#22]
Local network is stable, but open internet is not, especially for mobile environment. So if there is a variable to set, and simulate the package loss would be good.

**Comment by Jennal** [comment]
I find the code in `UNETTransport.cs`

```csharp
if (UnityEngine.Debug.isDebugBuild && m_isNetworkSimuationActive)
{
    var simulationConfig = new ConnectionSimulatorConfig(48, 50, 48, 50, 10);
    return NetworkTransport.ConnectWithSimulator(m_HostId, ip, port, 0, out error, simulationConfig);
}
else
     return NetworkTransport.Connect(m_HostId, ip, port, 0, out error);
```

How to setup `UnityEngine.Debug.isDebugBuild` and `m_isNetworkSimuationActive` ?

**Comment by pandr** [comment]
I believe it is the plan to have network condition simulation in our transport layer (https://github.com/Unity-Technologies/multiplayer) but I don't know of any timeframe. Meanwhile I recommend using Clumsy to simulate various conditions.

**Comment by Jennal** [comment]
Thank you for your reply. Clumsy is just awesome!
