### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by LiamDawe** [Unity-Technologies/FPSSample#4]
> Platforms    : Windows (client and server) and Linux (server only)

I assume Linux client support will be coming too?

**Comment by Memorix101** [comment]
https://forum.unity.com/threads/unity-on-linux-release-notes-and-known-issues.350256/page-2

**Comment by LiamDawe** [comment]
I am well aware that Unity has a Linux editor. I am talking specifically about the FPS Sample hence me being here.

**Comment by VikramBombhi** [comment]
@LiamDawe have you testes/plan on testing the FPS Sample on the Linux editor?

**Comment by LiamDawe** [comment]
No, i am simply asking a question.

**Comment by Memorix101** [comment]
You need to wait until 2018.3 is officially released, because the Linux experimental built is not in the Unity beta program.

**Comment by LiamDawe** [comment]
> You need to wait until 2018.3 is officially released, because the Linux experimental built is not in the Unity beta program.

What? There are beta builds of 2018.3 for Unity. Do you actually look up what you're talking about first? :)

**Comment by Memorix101** [comment]
Well, I'm sorry. I didn't know they have changed it. However, then I guess your question is obsolete. Download the latest Beta for Linux and get building. https://unity3d.com/unity/beta/2018.3.0b7

**Comment by LiamDawe** [comment]
My quote is quite literally from this GitHub page.

**Comment by win8linux** [comment]
Just to recap all of this:

* The FPS Sample supports Linux (server) but without client support
* @LiamDawe is asking the question of whether Linux client support will arrive for FPS Sample
* There ***is*** a Unity Beta for LInux (2018.3)

**Comment by Memorix101** [comment]
Sure, I understand you, but you seem not to understand me. To build the project you need a beta version of Unity. So, well you have one now. Download it, fetch the git and see if it works (Maybe the Unity people didn't test it) or is broken. If something is broken, report it so other people can work on it. This would be a wait better solution than calling me unhelpful and downvote nearly everything I wrote.

**Comment by LiamDawe** [comment]
Closing, I will speak to Unity another way, this is going in circles with unhelpful comments.

**Comment by Memorix101** [comment]
OK. This is what you get on OpenGL 4.5 and Vulkan ... seems the Rendering Pipeline is currently only working for DX11 (in this project). I guess this will change when PS4 support is coming. Also there is a stub for a Linux Player in the project files. So, it is a matter of time until Linux support is coming. Someone in the forums got it working on Mac, too (https://forum.unity.com/threads/problem-on-a-mac.573508/)
![vxc](https://user-images.githubusercontent.com/1466920/47502636-a1f22700-d868-11e8-8de0-1cb416249bb4.PNG) 
![screenshot 62](https://user-images.githubusercontent.com/1466920/47502851-08774500-d869-11e8-9218-468682e1c81d.png)

**Comment by bcvent** [comment]
@Memorix101 have you managed to try it with: 2018.4.x ?
