### ISSUE TITLE
3rd person  view ?

### ISSUE THREAD

**Issue by ralrigs** [Unity-Technologies/FPSSample#55]
Hey, is there a way to put it in TPS ?
TPS view could be great also

**Comment by communityus** [comment]
there is a console command, so F1 and then type in "thirdpersonview" if I recall it's on one of the doc pages.

What i haven't figured out yet is if there is a text config file I can put somewhere to do this out of the box, like say we wanted to use this as a template for ECS third person even though peeweek has one started, maybe we like this for longer term reasons. (or like the sample assets a lot :-) )

All i have figured out is that we can put our own values directly in the Game.cs entry point.

**Comment by ralrigs** [comment]
OMG thank you yeah its "thirdperson"

Great some peopple are more looking for the TPS than the FPS so that so great you have both in it 

OK thank you, ill check it 

Thank you so much again
