### ISSUE TITLE
The prefab "Robot_Ragdoll" miss the component "Skeleton", But the code try to get it?

### ISSUE THREAD

**Issue by VincentGogo** [Unity-Technologies/FPSSample#72]
Assets/Scripts/Game/Modules/Ragdoll/RagdollOwner.cs:51)
InitializeComponentSystem`1[T].OnUpdate () (at Assets/Scripts/ECS/BaseComponentDataSystem.cs:398)
Unity.Entities.ComponentSystem.InternalUpdate () (at Library/PackageCache/com.unity.entities@0.0.12-preview.24/Unity.Entities/ComponentSystem.cs:475)
Unity.Entities.ScriptBehaviourManager.Update () (at Library/PackageCache/com.unity.entities@0.0.12-preview.24/Unity.Entities/ScriptBehaviourManager.cs:83)
RagdollModule.HandleSpawning () (at Assets/Scripts/Game/Modules/Ragdoll/RagdollModule.cs:34)
PreviewGameLoop.PreviewTickUpdate () (at Assets/Scripts/Game/Main/PreviewGameLoop.cs:358)
PreviewGameLoop.UpdateStateActive () (at Assets/Scripts/Game/Main/PreviewGameLoop.cs:315)
StateMachine`1[T].Update () (at Assets/Scripts/Utils/StateMachine.cs:26)
PreviewGameLoop.Update () (at Assets/Scripts/Game/Main/PreviewGameLoop.cs:171)
Game.Update () (at Assets/Scripts/Game/Main/Game.cs:619)

**Comment by hnody2501** [comment]
May you contact me on discord?
ᴴᴸ IQEN#9897

**Comment by mikebdev** [comment]
Discord address: https://discord.gg/ebNEMz3

**Comment by VincentGogo** [comment]
Fixed it by click the menu "FPS Sample/Animation/Update Avatar References"

**Comment by VincentGogo** [comment]
> May you contact me on discord?
> ᴴᴸ IQEN#9897

Thanks, I just getted over it.

**Comment by mikebdev** [comment]
Thanks,

Mike Belcher
Senior Web Developer / Programmer
Phone: 410-202-8038
Email: MBDEV@outlook.com<mailto:MBDEV@outlook.com>
LinkedIn: http://www.linkedin.com/pub/mike-belcher/2a/599/b16
Web: http://www.MBDEVpro.com<http://www.mbdevpro.com/>
[MBDEVLogoSmall]
