### ISSUE TITLE
I have script compile errors related to HDRP + VFX

### ISSUE THREAD

**Issue by YiLuHuoHuaDaiShanDian** [Unity-Technologies/FPSSample#74]
![TIM截图20190615093837](https://user-images.githubusercontent.com/41221822/59545492-923b6600-8f51-11e9-8949-0241eee6c2ee.png)
Like this, there is no update button, And there are a lot of errors.

**Comment by roromaster** [comment]
Same here

**Comment by yajiedesign** [comment]
delete Packages\com.unity.render-pipelines.high-definition

**Comment by YiLuHuoHuaDaiShanDian** [comment]
> delete Packages\com.unity.render-pipelines.high-definition
![TIM截图20190616214350](https://user-images.githubusercontent.com/41221822/59565062-edb84180-9080-11e9-8ecf-117313adfd4c.png)
Thank you, you are right. But I have new problems.

**Comment by yajiedesign** [comment]
@YiLuHuoHuaDaiShanDian  i am same.many error..

**Comment by yajiedesign** [comment]
@YiLuHuoHuaDaiShanDian i am back to 2018.3.13. This version has the least error, but it still exists, and I don't know how to solve it.

**Comment by YiLuHuoHuaDaiShanDian** [comment]
@yajiedesign 你是不是中国人？

**Comment by Hsgngr** [comment]
Same here, please upgrade this project we fellas all need this.

**Comment by yajiedesign** [comment]
@yajiedesign 哈...换到2018.3.14能行

**Comment by olavito** [comment]
i don't think the dev team will fix their own screw-up, i'm getting the same issue

**Comment by YiLuHuoHuaDaiShanDian** [comment]
Everybody, You can download the 2018.3.8 version. If you want to use the new version of Unity, you need to handle it manually.
